language: java

addons:
  sonarcloud:
    organization: "umich-michr"
    token:
      secure: $SONAR_TOKEN

script:
  - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$SONAR_PROJECT_KEY